UPD: Adding the probe retrieval procedure
math-vrn/libtike-cufft pull request #10
Opened 2019-10-05 15:04 UTC by math-vrn

2019-10-05 15:10 UTC, math-vrn commented
@carterbox , could you review this?

2019-10-05 20:12 UTC, carterbox requested changes
I have suggested a mix of style and code robustness changes. I feel like there is more to this pull request that I haven't reviewed because `kerenels.cuh` was deleted, but it was not explained. I will look into the CUDA kernels next week because I think you pushed those changed related to solving the probe in an earlier commit to the master branch.

2019-10-05 20:12 UTC, carterbox commented on src/ptychocg/solver.py
> -        assert cp.isfinite(gammapsi), "The probe amplitude cannot be zero."
The probe amplitude cannot be zero in order to prevent zero division on lines 129 and 132, so we need to check that `cp.isfinite(cp.max(cp.abs(prb)))`.

2019-10-05 20:12 UTC, carterbox commented on src/ptychocg/solver.py
> +                        fprb-data*fprb/(cp.abs(fprb)**2+1e-32), scan, psi)/cp.max(cp.abs(psi))**2/self.nscan
What if model is neither 'gaussian' or 'poisson'? There should be an `else` which raises an error or one of these should be the default model.

2019-10-05 20:12 UTC, carterbox commented on src/ptychocg/solver.py
> +                        ((cp.sum(cp.conj(dprb)*(gradprb-gradprb0))))*dprb
Use parenthesis instead of backslash (`\`) to break mathematical statements [over multiple lines](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator).

2019-10-05 20:12 UTC, carterbox commented on src/ptychocg/solver.py
> -            if i == 0:
Why did you change the iteration counter from `i` to `k`?

2019-10-05 20:12 UTC, carterbox commented on tests/test.py
> +from scipy import ndimage
`ndimage` is already imported from `scipy`. This is redundant.

2019-10-07 16:09 UTC, carterbox requested changes
You should also update the version number to 0.2 because the solvers now require an additional parameter 'recover_prb'.

2019-10-08 02:14 UTC, merged

2019-10-08 17:14 UTC, carterbox commented
You accidentally(?) added some SWIG automatically generated files to the repository in those 5 commits.