ENH: move all cpu-gpu copy to the PtychoCufft class
math-vrn/libtike-cufft pull request #17
Opened 2019-10-27 14:29 UTC by math-vrn

move all cpu-gpu copy to functions fwd_ptycho_batch and run_batch, move all cupy calls from test.py

2019-10-27 14:29 UTC, math-vrn commented
@carterbox, please review

2019-10-27 16:14 UTC, carterbox requested changes
In this pull request, you restructure the test to give an actual pass/fail response based on whether the forward and adjunct operators are symmetric. :+1: 

You are also moving memory operations into the scope of the PtychoCuFFT class. It seems that you now assume that for batch forward and adjunct operations, the data is loaded from the host memory and is perhaps too large to fit in the GPU memory. This should be reflected in the documentation for the batch functions.

Requested Changes
---------------------------
- [ ]  Explain in the docs that the `batch` functions expect NumPy arrays instead of CuPy arrays and will cycle automatically transfer small groups of views to the GPU and back
- [ ] Test whether the new steps in `__init__` interfere with normal use of the non-batch forward and adjunct operators

2019-10-27 16:14 UTC, carterbox commented on src/ptychocg/solver.py
> +
I'm not sure that moving this code into the class is a good idea because it always overrides any memory settings that the end-user may want.

2019-10-28 15:02 UTC, nikitinvv commented
The latest pull request contains the following:
1) Replace fft type interpolation by linear interpolation
2) merge all types of probe/object multiplication into one kernel function 'muloperator' which operarates with global indices and and get the parameter flg=0,1,2 according to the multiplication type.
3) remove src files and functions related to shifts in the frequency domain
4) add test_adjoint.py script for checking the adjoint test for the ptycho operator with respect to object and the probe
5) switch version to 0.5.0

2019-10-28 15:02 UTC, nikitinvv commented
@carterbox, please review

2019-11-02 19:29 UTC, carterbox reviewed
This is nice work. It really makes those core operators more compact and easy to understand.

2019-11-02 19:29 UTC, carterbox commented on src/cuda/kernels.cu
> +  const int Ndetx, const int Ndety, int flg)
For readability, what do you think about defining an enumerated type with values `FORWARD`, `ADJOINT_OBJ`, `ADJOINT_PRB` instead of just passing integers. Alternatively, the meaning and possible values of `flg` should be described in the docstring above.

2019-11-02 19:29 UTC, carterbox commented on src/cuda/kernels.cu
> +  if (sx < 0 || sy < 0) return;
Should we also skip probe positions if `sx >= (N - Nprb) || sy >= (Nz - Nprb)`?

2019-11-02 22:54 UTC, carterbox commented
I believe this closes #5 because you implemented bilinear interpolation.

2019-11-04 17:22 UTC, math-vrn commented on src/cuda/kernels.cu
> +  const int Ndetx, const int Ndety, int flg)
agree

2019-11-04 17:23 UTC, math-vrn commented on src/cuda/kernels.cu
> +  if (sx < 0 || sy < 0) return;
yes

2019-11-16 14:50 UTC, merged